import { FormEvent, useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

type Namespace = { id: string; name: string; revision: number }
type Source = { id: string; external_id: string; formatted_text: string; raw_asr: string; occurred_at?: string; app?: string; processing_status: string; eligible: boolean; source_version: number }
type SourceDetail = Source & { chunks: { id: string; view: string; text: string }[]; memories: { id: string; kind: string; subject: string; predicate: string; value: string; state: string }[] }
type Memory = { id: string; kind: string; subject: string; predicate: string; value: string; scope: string; state: string }
type Evidence = { id: string; external_id: string; text: string; occurred_at?: string }
type Answer = { status: string; answer: string; draft_text?: string; evidence: Evidence[]; uncertainties: string[] }

async function api<T>(path: string, options?: RequestInit): Promise<T> {
  const response = await fetch(path, { headers: { 'Content-Type': 'application/json', ...(options?.headers || {}) }, ...options })
  const body = await response.json()
  if (!response.ok) throw new Error(body.message || body.detail?.message || 'Request failed')
  return body as T
}

function App() {
  const [namespaces, setNamespaces] = useState<Namespace[]>([])
  const [namespace, setNamespace] = useState<Namespace | null>(null)
  const [view, setView] = useState<'ask' | 'history' | 'memory' | 'import'>('ask')
  const [question, setQuestion] = useState('')
  const [answer, setAnswer] = useState<Answer | null>(null)
  const [sources, setSources] = useState<Source[]>([])
  const [memories, setMemories] = useState<Memory[]>([])
  const [selected, setSelected] = useState<SourceDetail | null>(null)
  const [jsonl, setJsonl] = useState('')
  const [notice, setNotice] = useState('')
  const [busy, setBusy] = useState(false)
  const refreshNamespaces = async () => { const all = await api<Namespace[]>('/api/namespaces'); setNamespaces(all); if (!namespace && all[0]) setNamespace(all[0]) }
  const refreshData = async (current = namespace) => {
    if (!current) return
    const [nextSources, nextMemories, nextNamespaces] = await Promise.all([api<Source[]>(`/api/namespaces/${current.id}/sources`), api<Memory[]>(`/api/namespaces/${current.id}/memories`), api<Namespace[]>('/api/namespaces')])
    setSources(nextSources); setMemories(nextMemories); setNamespaces(nextNamespaces); setNamespace(nextNamespaces.find(item => item.id === current.id) || current)
  }
  useEffect(() => { refreshNamespaces().catch(error => setNotice(error.message)) }, [])
  useEffect(() => { refreshData().catch(error => setNotice(error.message)) }, [namespace?.id])
  const createSpace = async () => { const used = new Set(namespaces.map(item => item.name.toLocaleLowerCase())); let number = Math.max(2, namespaces.length + 1); let name = namespaces.length ? `Memory ${number}` : 'My memory'; while (used.has(name.toLocaleLowerCase())) { number += 1; name = `Memory ${number}` } setBusy(true); try { const item = await api<Namespace>('/api/namespaces', { method: 'POST', body: JSON.stringify({ name }) }); setNamespace(item); setNotice(`Memory space “${item.name}” created.`) } catch (error) { setNotice((error as Error).message) } finally { setBusy(false) } }
  const submitAsk = async (event: FormEvent, mode: 'answer' | 'draft' = 'answer') => { event.preventDefault(); if (!namespace || !question.trim()) return; setBusy(true); setNotice(''); try { setAnswer(await api<Answer>(`/api/namespaces/${namespace.id}/ask`, { method: 'POST', body: JSON.stringify({ question, mode }) })) } catch (error) { setNotice((error as Error).message) } finally { setBusy(false) } }
  const importData = async (event: FormEvent) => { event.preventDefault(); if (!namespace || !jsonl.trim()) return; setBusy(true); try { const preview = await api<{ valid_count: number; invalid_count: number; errors: { line: number; message: string }[] }>(`/api/namespaces/${namespace.id}/imports/validate`, { method: 'POST', body: JSON.stringify({ jsonl }) }); if (preview.invalid_count) throw new Error(`Line ${preview.errors[0]?.line || '?'} is invalid. Fix the JSONL before importing.`); if (!preview.valid_count) throw new Error('No valid records found. Review the JSONL fields.'); const result = await api<{ accepted: number; conflicts: number }>(`/api/namespaces/${namespace.id}/imports`, { method: 'POST', body: JSON.stringify({ jsonl }) }); await api('/api/worker/drain', { method: 'POST' }); await refreshData(); if (result.accepted) setJsonl(''); setNotice(result.conflicts ? `Processed ${result.accepted} records; ${result.conflicts} changed IDs need explicit replacement.` : `Imported and processed ${result.accepted} records.`) } catch (error) { setNotice((error as Error).message) } finally { setBusy(false) } }
  const suppress = async (memory: Memory) => { if (!namespace) return; setBusy(true); try { await api(`/api/namespaces/${namespace.id}/memories/${memory.id}/suppressions`, { method: 'POST', body: JSON.stringify({ expected_revision: namespace.revision, operation_id: `ui-${crypto.randomUUID()}` }) }); await refreshData(); setNotice('This memory will no longer be used in answers.') } catch (error) { setNotice((error as Error).message) } finally { setBusy(false) } }
  const correct = async (memory: Memory) => { if (!namespace) return; const value = window.prompt('What should Kivi remember instead?', memory.value); if (!value?.trim()) return; setBusy(true); try { await api(`/api/namespaces/${namespace.id}/memories/${memory.id}/corrections`, { method: 'POST', body: JSON.stringify({ value, expected_revision: namespace.revision, operation_id: `ui-${crypto.randomUUID()}` }) }); await refreshData(); setNotice('Memory corrected. Future answers use the new value.') } catch (error) { setNotice((error as Error).message) } finally { setBusy(false) } }
  const deleteSource = async (source: Source) => { if (!namespace || !window.confirm(`Delete ${source.external_id}? Kivi will no longer be able to use its text.`)) return; setBusy(true); try { await api(`/api/namespaces/${namespace.id}/sources/${source.id}?expected_revision=${namespace.revision}&operation_id=ui-${crypto.randomUUID()}`, { method: 'DELETE' }); await refreshData(); setNotice('Source deleted and removed from future answers.') } catch (error) { setNotice((error as Error).message) } finally { setBusy(false) } }
  const inspect = async (source: Pick<Source, 'id'>) => { if (!namespace) return; setBusy(true); try { setSelected(await api<SourceDetail>(`/api/namespaces/${namespace.id}/sources/${source.id}`)) } catch (error) { setNotice((error as Error).message) } finally { setBusy(false) } }
  if (!namespace) return <main className="welcome"><div className="welcome-mark">kivi<span>MEMORY</span></div><p className="eyebrow">YOUR PRIVATE WORKSPACE</p><h1>Give Kivi a memory.</h1><p>Bring in your transcript history, recover the context behind an idea, and keep every answer connected to what you actually said.</p><button onClick={createSpace} disabled={busy}>{busy ? 'Creating workspace…' : 'Create a memory space'}</button><small>Local by default. You stay in control of every source and memory.</small>{notice && <p className="notice">{notice}</p>}</main>
  const readySources = sources.filter(source => source.eligible && source.processing_status === 'ready').length
  const activeMemories = memories.filter(memory => memory.state === 'active').length
  return <div className="app"><aside><div className="brand">kivi <small>MEMORY</small></div><p className="namespace">{namespace.name}</p><nav>{([['ask', 'Hey Kivi'], ['history', 'History'], ['memory', 'Memory'], ['import', 'Import']] as const).map(([id, label]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => { setView(id); setSelected(null) }}>{label}</button>)}</nav><div className="workspace-health"><span className="health-dot" />Memory ready<div>{readySources} sources · {activeMemories} active memories</div></div><div className="space-controls"><label>WORKSPACE<select value={namespace.id} onChange={event => setNamespace(namespaces.find(item => item.id === event.target.value) || null)}>{namespaces.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="quiet" onClick={createSpace}>+ New space</button></div></aside><main className="content">{notice && <div className="notice">{notice}</div>}{view === 'ask' && <Ask question={question} setQuestion={setQuestion} answer={answer} busy={busy} submit={submitAsk} sourceCount={readySources} memoryCount={activeMemories} inspect={inspect} />}{view === 'history' && <History sources={sources} busy={busy} deleteSource={deleteSource} inspect={inspect} />}{view === 'memory' && <MemoryList memories={memories} busy={busy} suppress={suppress} correct={correct} />}{view === 'import' && <Import jsonl={jsonl} setJsonl={setJsonl} busy={busy} submit={importData} />}</main>{selected && <SourceInspector source={selected} onClose={() => setSelected(null)} />}</div>
}

function Ask({ question, setQuestion, answer, busy, submit, sourceCount, memoryCount, inspect }: { question: string; setQuestion: (value: string) => void; answer: Answer | null; busy: boolean; submit: (event: FormEvent, mode?: 'answer' | 'draft') => void; sourceCount: number; memoryCount: number; inspect: (source: Pick<Source, 'id'>) => void }) { return <><header><p className="eyebrow">INTENTIONAL MEMORY</p><h1>Pick up where<br />you left off.</h1><p>Find something you said. See what changed. Prepare your next response with the record beside you.</p></header><form className="askbox" onSubmit={event => submit(event)}><textarea value={question} onChange={event => setQuestion(event.target.value)} placeholder="Ask about something you dictated…" /><div><small>Your history stays within this workspace.</small><span><button type="submit" disabled={busy}>{busy ? 'Looking…' : 'Ask Kivi'}</button><button type="button" className="secondary" disabled={busy} onClick={event => submit(event, 'draft')}>Draft an update</button></span></div></form>{!answer && <><section className="starter"><p className="eyebrow">A PLACE TO START</p><button onClick={() => setQuestion('What changed in the latest project update?')}>What changed about the launch?</button><button onClick={() => setQuestion('What preferences have I mentioned?')}>What preferences have I mentioned?</button></section><section className="memory-stats"><article><strong>{sourceCount}</strong><span>searchable sources</span></article><article><strong>{memoryCount}</strong><span>active memory candidates</span></article><article><strong>1 click</strong><span>back to the source</span></article></section></>}{answer && <section className="answer"><p className="eyebrow">{answer.status.replace('_', ' ')}</p><h2>{answer.draft_text ? 'Draft an update' : 'A useful answer, with a path back to what you said.'}</h2><p className="answer-text">{answer.draft_text || answer.answer}</p>{answer.evidence.length > 0 && <><h3>Sources behind this answer</h3><div className="sources">{answer.evidence.map((source, index) => <button type="button" className="source-evidence" disabled={busy} onClick={() => inspect(source)} key={source.id}><strong>{index + 1} · {source.external_id}</strong><p>{source.text}</p><small>Inspect source →</small></button>)}</div></>}{answer.uncertainties.map(item => <p className="uncertainty" key={item}>{item}</p>)}</section>}</> }
function History({ sources, deleteSource, inspect, busy }: { sources: Source[]; deleteSource: (source: Source) => void; inspect: (source: Source) => void; busy: boolean }) { return <><header><p className="eyebrow">HISTORY</p><h1>What Kivi can look back on.</h1><p>Each entry keeps the raw dictation and its cleaned transcript together.</p></header>{sources.length ? <div className="cards">{sources.map(source => { const visibleStatus = source.eligible ? source.processing_status : 'replaced'; return <article className="card" key={source.id}><div><strong>{source.external_id} · v{source.source_version}</strong><span className={`status ${visibleStatus}`}>{visibleStatus}</span></div><p>{source.formatted_text || source.raw_asr || 'Empty transcript record'}</p><small>{source.occurred_at ? new Date(source.occurred_at).toLocaleString() : 'Time unknown'}{source.app ? ` · ${source.app}` : ''}</small><footer><button className="quiet" disabled={busy} onClick={() => inspect(source)}>Inspect source</button><button className="quiet danger" disabled={busy} onClick={() => deleteSource(source)}>Delete</button></footer></article> })}</div> : <Empty text="Import a transcript history to see it here." />}</> }
function MemoryList({ memories, suppress, correct, busy }: { memories: Memory[]; suppress: (memory: Memory) => void; correct: (memory: Memory) => void; busy: boolean }) { return <><header><p className="eyebrow">SCOPED MEMORY</p><h1>Facts and preferences Kivi learned.</h1><p>Each item remains tied to the source that supported it.</p></header>{memories.length ? <div className="cards">{memories.map(memory => <article className="card" key={memory.id}><div><strong>{memory.kind}</strong><span className={`status ${memory.state}`}>{memory.state}</span></div><p>{memory.subject} · {memory.predicate} · <b>{memory.value}</b></p><small>Scope: {memory.scope}</small>{memory.state === 'active' && <footer><button className="quiet" disabled={busy} onClick={() => correct(memory)}>Correct</button><button className="quiet danger" disabled={busy} onClick={() => suppress(memory)}>Stop using</button></footer>}</article>)}</div> : <Empty text="Kivi has not promoted any conservative memory candidates yet. Sources are still searchable." />}</> }
function Import({ jsonl, setJsonl, busy, submit }: { jsonl: string; setJsonl: (value: string) => void; busy: boolean; submit: (event: FormEvent) => void }) { return <><header><p className="eyebrow">IMPORT</p><h1>Bring in a transcript history.</h1><p>Paste UTF-8 JSONL using the documented v1 record format. Source text is retained exactly.</p></header><form className="import" onSubmit={submit}><textarea value={jsonl} onChange={event => setJsonl(event.target.value)} placeholder={'{"schema_version":1,"id":"note-001","raw_asr":"lantern launch monday","formatted_text":"Lantern launches Monday."}'} /><button disabled={busy}>{busy ? 'Importing…' : 'Validate, import, and process'}</button></form></> }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div> }
function SourceInspector({ source, onClose }: { source: SourceDetail; onClose: () => void }) { return <aside className="inspector" aria-label="Source inspector"><button className="close" onClick={onClose}>×</button><p className="eyebrow">SOURCE INSPECTOR</p><h2>{source.external_id}</h2><p className="source-meta">{source.occurred_at ? new Date(source.occurred_at).toLocaleString() : 'Time unknown'}{source.app ? ` · ${source.app}` : ''}</p><h3>Formatted transcript</h3><p>{source.formatted_text || 'No formatted transcript supplied.'}</p><h3>Raw dictation</h3><p>{source.raw_asr || 'No raw ASR supplied.'}</p><h3>Indexed passages</h3>{source.chunks.length ? source.chunks.map(chunk => <p className="chunk" key={chunk.id}>{chunk.text}</p>) : <p>No passages indexed yet.</p>}<h3>Memories derived here</h3>{source.memories.length ? source.memories.map(memory => <p className="chunk" key={memory.id}>{memory.subject} · {memory.predicate} · {memory.value} <em>{memory.state}</em></p>) : <p>No conservative memory candidates were promoted.</p>}</aside> }

createRoot(document.getElementById('root')!).render(<App />)
